# Generated by Django 4.1.2 on 2023-04-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem',
            new_name='Usuario',
        ),
    ]
